CONFIG += staticlib silent
#		  precompile_header \

QT += opengl
TEMPLATE = lib
DEPENDPATH += .
INCLUDEPATH += . \
	"../include" \
	"../contrib" \
	"$$(SEEDSDK)/dependency/common/include" \
	"$$(SEEDSDK)/dependency/mingw/include"
DEFINES += _QT_
Debug {
	OBJECTS_DIR = ../bin/debug/qt/obj
	DESTDIR = ../bin/debug/qt
	MOC_DIR = ../bin/debug/qt/moc
	DEFINES += DEBUG
}
Release {
	DESTDIR = ../bin/release/qt
	OBJECTS_DIR = ../bin/release/qt/obj
	MOC_DIR = ../bin/release/qt/moc
	DEFINES += RELEASE
}

PRECOMPILED_HEADER = ../include/platform/qt/QtPch.h

# Windows
win32:DEFINES += WIN32 _WIN32_
HEADERS += ../include/api/directx/D3D8RendererDevice.h \
	../include/api/directx/DirectXVersion.h \
	../include/api/oal_ogg/OalOggMusic.h \
	../include/api/oal_ogg/OalOggSound.h \
	../include/api/oal_ogg/OalOggSoundSource.h \
	../include/api/oal_ogg/OalOggSoundSystem.h \
	../include/api/oal_ogg/vorbis_util.h \
	../include/api/ogl/Ogl14RendererDevice.h \
	../include/api/ogl/OglES1RendererDevice.h \
	../include/api/theora/Theora.h \
	../include/Array.h \
	../include/Base.h \
	../include/Cartridge.h \
	../include/Checksum.h \
	../include/CollisionMask.h \
	../include/Config.h \
	../include/Configuration.h \
	../include/Defines.h \
	../include/Dictionary.h \
	../include/Enum.h \
	../include/EventFileSystem.h \
	../include/EventInputKeyboard.h \
	../include/EventInputMotion.h \
	../include/EventInputPointer.h \
	../include/EventMovie.h \
	../include/EventResourceLoader.h \
	../include/EventSystem.h \
	../include/extra/ymanager/yallocwrap.h \
	../include/extra/ymanager/ydefines.h \
	../include/extra/ymanager/ymemorymanager.h \
	../include/File.h \
	../include/Font.h \
	../include/Formats.h \
	../include/gui/Button.h \
	../include/gui/EventWidget.h \
	../include/gui/GuiManager.h \
	../include/gui/Label.h \
	../include/gui/TextArea.h \
	../include/gui/WidgetContainer.h \
	../include/Image.h \
	../include/Input.h \
	../include/interface/IInputKeyboard.h \
	../include/interface/IBasicMesh.h \
	../include/interface/ICartridge.h \
	../include/interface/IEvent.h \
	../include/interface/IEventFileSystemListener.h \
	../include/interface/IEventInput.h \
	../include/interface/IEventInputKeyboardListener.h \
	../include/interface/IEventInputMotionListener.h \
	../include/interface/IEventInputPointerListener.h \
	../include/interface/IEventListener.h \
	../include/interface/IEventMovieListener.h \
	../include/interface/IEventResourceLoaderListener.h \
	../include/interface/IEventSystemListener.h \
	../include/interface/IEventWidgetListener.h \
	../include/interface/IFileSystem.h \
	../include/interface/IGameApp.h \
	../include/interface/IInput.h \
	../include/interface/IInputJoystick.h \
	../include/interface/IInputMotion.h \
	../include/interface/IInputPointer.h \
	../include/interface/IMemoryManager.h \
	../include/interface/IMemoryPool.h \
	../include/interface/IModule.h \
	../include/interface/IMusic.h \
	../include/interface/IMutex.h \
	../include/interface/IObject.h \
	../include/interface/IPlayable.h \
	../include/interface/IRenderable.h \
	../include/interface/IRendererDevice.h \
	../include/interface/IResource.h \
	../include/interface/ISceneNode.h \
	../include/interface/ISceneObject.h \
	../include/interface/IScreen.h \
	../include/interface/ISound.h \
	../include/interface/ISoundSource.h \
	../include/interface/ISoundSystem.h \
	../include/interface/ISprite.h \
	../include/interface/ISystem.h \
	../include/interface/ITexture.h \
	../include/interface/IThread.h \
	../include/interface/ITimer.h \
	../include/interface/ITransformable2D.h \
	../include/interface/IUpdatable.h \
	../include/interface/IVideo.h \
	../include/interface/IWidget.h \
	../include/Key.h \
	../include/Keyframe.h \
	../include/LeakReport.h \
	../include/Log.h \
	../include/MathUtil.h \
	../include/Matrix4x4.h \
	../include/MemoryManager.h \
	../include/MemoryPool.h \
	../include/ModuleManager.h \
	../include/Movie.h \
	../include/Music.h \
	../include/Mutex.h \
	../include/Number.h \
	../include/Package.h \
	../include/Particle.h \
	../include/ParticleEmitter.h \
	../include/ParticleEmitterObject.h \
	../include/ParticleManager.h \
	../include/platform/iphone/IphDefines.h \
	../include/platform/iphone/IphInput.h \
	../include/platform/iphone/IphMusic.h \
	../include/platform/iphone/IphMutex.h \
	../include/platform/iphone/IphoneSystemStub.h \
	../include/platform/iphone/IphoneView.h \
	../include/platform/iphone/IphScreen.h \
	../include/platform/iphone/IphSound.h \
	../include/platform/iphone/IphSoundSource.h \
	../include/platform/iphone/IphSoundSystem.h \
	../include/platform/iphone/IphSystem.h \
	../include/platform/iphone/IphTexture.h \
	../include/platform/iphone/IphThread.h \
	../include/platform/iphone/IphTimer.h \
	../include/platform/pc/PcCartridge.h \
	../include/platform/pc/PcFileSystem.h \
	../include/platform/pc/PcMemoryManager.h \
	../include/platform/pc/PcMemoryPool.h \
	../include/platform/pc/PcRendererDevice.h \
	../include/platform/pc/platform.h \
	../include/platform/qt/QtDefines.h \
	../include/platform/qt/QtInput.h \
	../include/platform/qt/QtMutex.h \
	../include/platform/qt/QtPch.h \
	../include/platform/qt/QtScene.h \
	../include/platform/qt/QtScreen.h \
	../include/platform/qt/QtSurface.h \
	../include/platform/qt/QtSystem.h \
	../include/platform/qt/QtTexture.h \
	../include/platform/qt/QtThread.h \
	../include/platform/qt/QtTimer.h \
	../include/platform/sdl/SdlDefines.h \
	../include/platform/sdl/SdlInput.h \
	../include/platform/sdl/SdlMutex.h \
	../include/platform/sdl/SdlScreen.h \
	../include/platform/sdl/SdlSystem.h \
	../include/platform/sdl/SdlTexture.h \
	../include/platform/sdl/SdlThread.h \
	../include/platform/sdl/SdlTimer.h \
	../include/platform/wii/WiiCartridge.h \
	../include/platform/wii/WiiDefines.h \
	../include/platform/wii/WiiFileSystem.h \
	../include/platform/wii/WiiHomeButton.h \
	../include/platform/wii/WiiImage.h \
	../include/platform/wii/WiiInput.h \
	../include/platform/wii/WiiMemoryManager.h \
	../include/platform/wii/WiiMusic.h \
	../include/platform/wii/WiiMutex.h \
	../include/platform/wii/WiiRenderer.h \
	../include/platform/wii/WiiRenderer2D.h \
	../include/platform/wii/WiiScreen.h \
	../include/platform/wii/WiiSound.h \
	../include/platform/wii/WiiSoundHelper.h \
	../include/platform/wii/WiiSoundSource.h \
	../include/platform/wii/WiiSoundSystem.h \
	../include/platform/wii/WiiSprite.h \
	../include/platform/wii/WiiSystem.h \
	../include/platform/wii/WiiTexture.h \
	../include/platform/wii/WiiThread.h \
	../include/platform/wii/WiiTimer.h \
	../include/platform/wii/WiiWrapper.h \
	../include/Point.h \
	../include/Profiler.h \
	../include/Quaternion.h \
	../include/Rand.h \
	../include/Rect.h \
	../include/Renderer.h \
	../include/Renderer2D.h \
	../include/RendererDevice.h \
	../include/RendererManager.h \
	../include/ResourceGroup.h \
	../include/ResourceLoader.h \
	../include/ResourceManager.h \
	../include/SaveSystem.h \
	../include/SceneManager.h \
	../include/Screen.h \
	../include/Seed.h \
	../include/SeedInit.h \
	../include/Singleton.h \
	../include/Sound.h \
	../include/SoundSource.h \
	../include/SoundSystem.h \
	../include/Sprite.h \
	../include/SpriteObject.h \
	../include/StateMachine.h \
	../include/StringCache.h \
	../include/StringPool.h \
	../include/System.h \
	../include/Text.h \
	../include/Texture.h \
	../include/Thread.h \
	../include/Timeline.h \
	../include/Timer.h \
	../include/Trigonometry.h \
	../include/TString.h \
	../include/Updater.h \
	../include/Vector.h \
	../include/Vector3.h \
	../include/Vertex.h \
	../include/ViewManager.h \
	../include/Viewport.h \
	../include/FileSystem.h \
	../include/PackageManager.h \
	../include/SceneNode.h \
	../contrib/nedmalloc.h \
	../contrib/nedtrie.h \
	../include/platform/qt/QtPch.h

SOURCES += ../source/LeakReport.cpp \
	../source/api/directx/D3D8RendererDevice.cpp \
	../source/api/directx/DirectXVersion.cpp \
	../source/api/oal_ogg/OalOggMusic.cpp \
	../source/api/oal_ogg/OalOggSound.cpp \
	../source/api/oal_ogg/OalOggSoundSource.cpp \
	../source/api/oal_ogg/OalOggSoundSystem.cpp \
	../source/api/oal_ogg/vorbis_util.cpp \
	../source/api/ogl/Ogl14RendererDevice.cpp \
	../source/api/ogl/OglES1RendererDevice.cpp \
	../source/api/theora/Theora.cpp \
	../source/Checksum.cpp \
	../source/CollisionMask.cpp \
	../source/Configuration.cpp \
	../source/Dictionary.cpp \
	../source/EventFileSystem.cpp \
	../source/EventInputKeyboard.cpp \
	../source/EventInputMotion.cpp \
	../source/EventInputPointer.cpp \
	../source/EventMovie.cpp \
	../source/EventResourceLoader.cpp \
	../source/EventSystem.cpp \
	../source/extra/ymanager/yallocwrap.cpp \
	../source/extra/ymanager/ymemorymanager.cpp \
	../source/File.cpp \
	../source/Font.cpp \
	../source/Formats.cpp \
	../source/gui/Button.cpp \
	../source/gui/EventWidget.cpp \
	../source/gui/GuiManager.cpp \
	../source/gui/Label.cpp \
	../source/gui/TextArea.cpp \
	../source/gui/WidgetContainer.cpp \
	../source/Image.cpp \
	../source/interface/IInputJoystick.cpp \
	../source/interface/IBasicMesh.cpp \
	../source/interface/ICartridge.cpp \
	../source/interface/IEvent.cpp \
	../source/interface/IEventFileSystemListener.cpp \
	../source/interface/IEventInput.cpp \
	../source/interface/IEventInputKeyboardListener.cpp \
	../source/interface/IEventInputMotionListener.cpp \
	../source/interface/IEventInputPointerListener.cpp \
	../source/interface/IEventListener.cpp \
	../source/interface/IEventMovieListener.cpp \
	../source/interface/IEventResourceLoaderListener.cpp \
	../source/interface/IEventSystemListener.cpp \
	../source/interface/IEventWidgetListener.cpp \
	../source/interface/IFileSystem.cpp \
	../source/interface/IGameApp.cpp \
	../source/interface/IInput.cpp \
	../source/interface/IInputKeyboard.cpp \
	../source/interface/IInputMotion.cpp \
	../source/interface/IInputPointer.cpp \
	../source/interface/IMemoryManager.cpp \
	../source/interface/IMemoryPool.cpp \
	../source/interface/IModule.cpp \
	../source/interface/IMusic.cpp \
	../source/interface/IMutex.cpp \
	../source/interface/IObject.cpp \
	../source/interface/IPlayable.cpp \
	../source/interface/IRenderable.cpp \
	../source/interface/IRendererDevice.cpp \
	../source/interface/IResource.cpp \
	../source/interface/ISceneNode.cpp \
	../source/interface/ISceneObject.cpp \
	../source/interface/IScreen.cpp \
	../source/interface/ISound.cpp \
	../source/interface/ISoundSource.cpp \
	../source/interface/ISoundSystem.cpp \
	../source/interface/ISprite.cpp \
	../source/interface/ISystem.cpp \
	../source/interface/ITexture.cpp \
	../source/interface/IThread.cpp \
	../source/interface/ITimer.cpp \
	../source/interface/ITransformable2D.cpp \
	../source/interface/IUpdatable.cpp \
	../source/interface/IVideo.cpp \
	../source/interface/IWidget.cpp \
	../source/Key.cpp \
	../source/Keyframe.cpp \
	../source/ModuleManager.cpp \
	../source/Movie.cpp \
	../source/Package.cpp \
	../source/PackageManager.cpp \
	../source/Particle.cpp \
	../source/ParticleEmitter.cpp \
	../source/ParticleEmitterObject.cpp \
	../source/ParticleManager.cpp \
	../source/platform/iphone/IphInput.cpp \
	../source/platform/iphone/IphMusic.cpp \
	../source/platform/iphone/IphMutex.cpp \
	../source/platform/iphone/IphScreen.cpp \
	../source/platform/iphone/IphSound.cpp \
	../source/platform/iphone/IphSoundSource.cpp \
	../source/platform/iphone/IphSoundSystem.cpp \
	../source/platform/iphone/IphSystem.cpp \
	../source/platform/iphone/IphTexture.cpp \
	../source/platform/iphone/IphThread.cpp \
	../source/platform/iphone/IphTimer.cpp \
	../source/platform/pc/PcCartridge.cpp \
	../source/platform/pc/PcFileSystem.cpp \
	../source/platform/pc/PcLog.cpp \
	../source/platform/pc/PcMemoryManager.cpp \
	../source/platform/pc/PcMemoryPool.cpp \
	../source/platform/pc/PcRendererDevice.cpp \
	../source/platform/pc/posix.cpp \
	../source/platform/pc/win32.cpp \
	../source/platform/qt/QtInput.cpp \
	../source/platform/qt/QtMutex.cpp \
	../source/platform/qt/QtScene.cpp \
	../source/platform/qt/QtScreen.cpp \
	../source/platform/qt/QtSurface.cpp \
	../source/platform/qt/QtSystem.cpp \
	../source/platform/qt/QtTexture.cpp \
	../source/platform/qt/QtThread.cpp \
	../source/platform/qt/QtTimer.cpp \
	../source/platform/sdl/SdlInput.cpp \
	../source/platform/sdl/SdlMutex.cpp \
	../source/platform/sdl/SdlScreen.cpp \
	../source/platform/sdl/SdlSystem.cpp \
	../source/platform/sdl/SdlTexture.cpp \
	../source/platform/sdl/SdlThread.cpp \
	../source/platform/sdl/SdlTimer.cpp \
	../source/Profiler.cpp \
	../source/Rand.cpp \
	../source/Renderer.cpp \
	../source/RendererManager.cpp \
	../source/ResourceGroup.cpp \
	../source/ResourceLoader.cpp \
	../source/ResourceManager.cpp \
	../source/SaveSystem.cpp \
	../source/SceneManager.cpp \
	../source/SceneNode.cpp \
	../source/SeedInit.cpp \
	../source/SpriteObject.cpp \
	../source/StringCache.cpp \
	../source/Text.cpp \
	../source/Timeline.cpp \
	../source/Trigonometry.cpp \
	../source/TString.cpp \
	../source/Updater.cpp \
	../source/ViewManager.cpp \
	../source/Viewport.cpp \
	../contrib/nedmalloc/nedmalloc.c
